# This workflow is used to benchmark a Rust project
name: cargo-bench
# The workflow may be manually triggered and is run automatically when:
# - a pull request is closed on the default branch (main/master)
# - a release is published
# - a repository_dispatch event with the type "cargo-bench" is received

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - latest
      - v[0-9]*
      - v[0-9]*.[0-9]*.[0-9]*
  repository_dispatch:
    types: [ cargo-bench ]
  workflow_dispatch:
    inputs:
      runner:
        default: self-hosted
        description: What type of runner should the action leverage?
        type: choice
        options: [macos-latest, ubuntu-latest, windows-latest, self-hosted]
      target:
        default: x86_64-unknown-linux-gnu
        description: "Select the target to compile for"
        required: false
      toolchain:
        default: stable
        description: "Select a toolchain to test (stable, nightly)"
        required: true
        type: choice
        options: [stable, nightly]

jobs:
  benchmark:
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    env:
      CACHE_ON_FAILURE: true
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true
    permissions:
      actions: write
      checks: write
      contents: write
    outputs:
      id: ${{ steps.artifacts.outputs.artifact-id }}
      digest: ${{ steps.artifacts.outputs.artifact-digest }}
      url: ${{ steps.artifacts.outputs.artifact-url }}
    strategy:
      fail-fast: false
      matrix:
        features: [ full ]
        include:
          - target: ${{ github.event.inputs.target || 'x86_64-unknown-linux-gnu' }}
            toolchain: ${{ github.event.inputs.toolchain || 'stable' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          fetch-tags: true
          ref: ${{ github.event.client_payload.ref  || github.ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare the workflow
        run: |
          if [[ "${{ matrix.toolchain }}" == "nightly" ]]; then
            echo "RUSTFLAGS=-C panic=abort -Z panic_abort_tests" >> $GITHUB_ENV
          fi
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10
      # 2. Add rust-cache here to manage your registry index and crate downloads
      - name: Setup rust-cache
        uses: swatinem/rust-cache@v2
        with:
          key: cargo-${{ matrix.toolchain }}-${{ matrix.target }}-${{ matrix.features }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache: false
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install cargo-criterion
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-criterion
      - name: Benchmark (${{ matrix.target }})
        run: |
          cargo criterion --benches --locked --verbose --workspace \
            --features ${{ matrix.features }} \
            --target ${{ matrix.target }}
      - name: Upload the benchmarks
        id: artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Benchmark Report (${{ github.run_id }})
          if-no-files-found: error
          overwrite: true
          path: target/criterion/
